name: Compile firmwares - split
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop  
jobs:
  nrf52832:
    runs-on: self-hosted
    container: jpconstantineau/arduino-cli-bluefruit-nrf52
    steps:
    - uses: actions/checkout@v2
    - name: Build nrf52832
      run: ./build/docker/gha-nrf.sh nrf52832:all:all:all
  nrf52840:
    runs-on: self-hosted
    container: jpconstantineau/arduino-cli-bluefruit-nrf52
    steps:
    - uses: actions/checkout@v2
    - name: Build nr52840
      run: ./build/docker/gha-nrf.sh nr52840:all:all:all
